"""Club-local evidence, observations, capacity and deterministic reports."""

from .coverage import observation_task_id, record_match_observations
from .metrics import CORE_METRICS, MetricAggregation, MetricDefinition, MetricRegistry
from .model import (
    CoverageGrant,
    CoverageLevel,
    FieldRequest,
    MetricFinding,
    Observation,
    ObservationLedger,
    Report,
    ReportCache,
    ReportFieldFinding,
    ReportQuery,
    StaffCapacity,
    StaffRole,
    StaffSchedule,
    StaffWorkAssignment,
    assign_staff_work,
    record_observations,
)
from .reports import build_report
from .scouting import (
    CandidateComparison,
    CandidateFinding,
    ComparisonOutcome,
    DossierDimension,
    DossierDimensionStatus,
    EvidenceSlice,
    MatchEvidenceReplay,
    OppositionBrief,
    Recommendation,
    RecruitmentDossier,
    RoleProfile,
    RoleSearchReport,
    ScoutingQuery,
    compare_candidates,
    build_recruitment_dossier,
    opposition_brief,
    replay_comparison,
    replay_opposition_brief,
    replay_role_search,
    replay_dossier,
    role_search,
)

__all__ = [
    "CORE_METRICS",
    "CoverageGrant",
    "CoverageLevel",
    "CandidateComparison",
    "CandidateFinding",
    "ComparisonOutcome",
    "DossierDimension",
    "DossierDimensionStatus",
    "EvidenceSlice",
    "FieldRequest",
    "MetricAggregation",
    "MetricDefinition",
    "MetricFinding",
    "MetricRegistry",
    "MatchEvidenceReplay",
    "OppositionBrief",
    "Observation",
    "ObservationLedger",
    "Report",
    "ReportCache",
    "ReportFieldFinding",
    "ReportQuery",
    "Recommendation",
    "RecruitmentDossier",
    "RoleProfile",
    "RoleSearchReport",
    "ScoutingQuery",
    "StaffCapacity",
    "StaffRole",
    "StaffSchedule",
    "StaffWorkAssignment",
    "assign_staff_work",
    "build_report",
    "observation_task_id",
    "compare_candidates",
    "build_recruitment_dossier",
    "opposition_brief",
    "replay_comparison",
    "replay_opposition_brief",
    "replay_role_search",
    "replay_dossier",
    "record_match_observations",
    "record_observations",
    "role_search",
]
